[profile.default]
src = "src"
out = "out"
test = "test"
script = "script"
cache_path = "cache"
broadcast = "broadcast"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200


remappings = [
  "@interop-lib/=lib/interop-lib/src/",
  "@solady/=lib/solady/src/",
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@createx/=lib/createx/src/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "forge-std/=lib/forge-std/src/",
  "@pythnetwork/pyth-sdk-solidity/=lib/pyth-sdk-solidity/",
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
mainnet = "https://rpc.ankr.com/eth"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"

[fuzz]
runs = 256
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

# Fork testing configuration
[profile.default.fuzz]
runs = 10

[profile.default.invariant]
runs = 10
depth = 15
fail_on_revert = false
